### ISSUE TITLE
초기 프로젝트 진행을 위한 환경 설정

### ISSUE THREAD

**Issue by Seok93** [FC7-FE/bulletin-board#1]
## Description
초기 프로젝트 설정

## Todo
- [x] CRA로 프로젝트 생성
- [x] 불필요한 이미지 파일 삭제
- [x] 라이브러리 설치 ( axios, styled-components, react-router, redux, react-redux, @reduxjs/toolkit)
- [x]  README 파일 작업
- [x] Github Issue, PR 템플릿 설정
- [x] Prettier 설정
