### ISSUE TITLE
회원가입 컴포넌트

### ISSUE THREAD

**Issue by Hungeun2** [FC7-FE/bulletin-board#4]
#### 회원가입 컴포넌트
1. API를 활용한 중복 ID검사
2. `ID`, `NAME`, `PW`, `PW확인` 4개의 입력필드
- `ID` : 4자리 이상의 알파벳 및 숫자
- `PW` : 특수문자 사용불가 및 8자 이상
3. 가입 성공 여부 피드백

## Todo List
- [ ] HTML/CSS 작성
- [ ] 정규표현식 사용한 ID, PW Valid Check
- [ ] 회원가입 성공시 리다이렉트?
